/**
 * App icons, drawn from Hugeicons (hugeicons.com, free stroke set).
 * Components keep lucide-style names and props (className, size, strokeWidth) so call sites stay unchanged.
 */
import { HugeiconsIcon, type HugeiconsIconProps } from "@hugeicons/react"
import * as H from "@hugeicons/core-free-icons"

export type IconProps = Omit<React.SVGProps<SVGSVGElement>, "ref" | "strokeWidth"> & { size?: number | string; strokeWidth?: number | string }
export type Icon = (props: IconProps) => React.JSX.Element

const make = (icon: HugeiconsIconProps["icon"]): Icon => {
  const C = (props: IconProps) => <HugeiconsIcon icon={icon} {...(props as Omit<HugeiconsIconProps, "icon">)} strokeWidth={Number(props.strokeWidth ?? 1.75)} />
  return C
}

export const AlertCircle = make(H.AlertCircleIcon)
export const ArrowDown = make(H.ArrowDown02Icon)
export const ArrowLeft = make(H.ArrowLeft02Icon)
export const ArrowRight = make(H.ArrowRight02Icon)
export const ArrowUp = make(H.ArrowUp02Icon)
export const AudioLines = make(H.AudioWave01Icon)
export const Camera = make(H.Camera01Icon)
export const Check = make(H.Tick02Icon)
export const CheckIcon = make(H.Tick02Icon)
export const ChevronDown = make(H.ArrowDown01Icon)
export const ChevronDownIcon = make(H.ArrowDown01Icon)
export const ChevronRightIcon = make(H.ArrowRight01Icon)
export const ChevronUpIcon = make(H.ArrowUp01Icon)
export const Circle = make(H.CircleIcon)
export const CircleCheckIcon = make(H.CheckmarkCircle02Icon)
export const CircleHelp = make(H.HelpCircleIcon)
export const CircleIcon = make(H.CircleIcon)
export const Copy = make(H.Copy01Icon)
export const Cpu = make(H.CpuIcon)
export const Diamond = make(H.DiamondIcon)
export const ExternalLink = make(H.LinkSquare02Icon)
export const Eye = make(H.ViewIcon)
export const EyeOff = make(H.ViewOffSlashIcon)
export const FileJson = make(H.CodeSquareIcon)
export const FileStack = make(H.Files02Icon)
export const FileText = make(H.File01Icon)
export const Flag = make(H.Flag02Icon)
export const GalleryHorizontalEnd = make(H.LibraryIcon)
export const GripVerticalIcon = make(H.DragDropVerticalIcon)
export const Hand = make(H.Hold04Icon)
export const Home = make(H.Home01Icon)
export const Image = make(H.Image01Icon)
export const ImageIcon = make(H.Image01Icon)
export const ImagePlus = make(H.ImageAdd01Icon)
export const Images = make(H.Image02Icon)
export const InfoIcon = make(H.InformationCircleIcon)
export const KeyRound = make(H.Key01Icon)
export const Layers = make(H.Layers01Icon)
export const LayoutGrid = make(H.GridViewIcon)
export const List = make(H.ListViewIcon)
export const ListTodo = make(H.CheckListIcon)
export const Loader2 = make(H.Loading03Icon)
export const Loader2Icon = make(H.Loading03Icon)
export const LoaderCircle = make(H.Loading03Icon)
export const LockKeyhole = make(H.LockKeyIcon)
export const LogIn = make(H.Login03Icon)
export const LogOut = make(H.Logout03Icon)
export const Maximize = make(H.FullScreenIcon)
export const Maximize2 = make(H.ArrowExpand01Icon)
export const MessageCircle = make(H.Comment01Icon)
export const MessageSquarePlus = make(H.MessageAdd01Icon)
export const MessageSquareText = make(H.Message01Icon)
export const Mic = make(H.Mic01Icon)
export const MicOff = make(H.MicOff01Icon)
export const Minus = make(H.MinusSignIcon)
export const Monitor = make(H.ComputerIcon)
export const MoreHorizontal = make(H.MoreHorizontalIcon)
export const MousePointer2 = make(H.Cursor01Icon)
export const OctagonXIcon = make(H.CancelCircleIcon)
export const Package = make(H.PackageIcon)
export const Palette = make(H.PaintBoardIcon)
export const PanelLeftIcon = make(H.SidebarLeftIcon)
export const Paperclip = make(H.Attachment01Icon)
export const PenLine = make(H.PencilEdit02Icon)
export const Pencil = make(H.PencilEdit01Icon)
export const PhoneOff = make(H.CallEnd01Icon)
export const Play = make(H.PlayIcon)
export const Plug = make(H.Plug01Icon)
export const Plus = make(H.PlusSignIcon)
export const Radio = make(H.RadioIcon)
export const Redo2 = make(H.Redo02Icon)
export const RefreshCw = make(H.RefreshIcon)
export const RotateCcw = make(H.ArrowTurnBackwardIcon)
export const Search = make(H.Search01Icon)
export const SearchIcon = make(H.Search01Icon)
export const Send = make(H.SentIcon)
export const Settings2 = make(H.Settings02Icon)
export const Shapes = make(H.FigmaIcon)
export const Sparkles = make(H.SparklesIcon)
export const Square = make(H.SquareIcon)
export const Star = make(H.StarIcon)
export const StickyNote = make(H.StickyNote01Icon)
export const Trash2 = make(H.Delete02Icon)
export const Triangle = make(H.TriangleIcon)
export const TriangleAlertIcon = make(H.Alert02Icon)
export const Undo2 = make(H.Undo02Icon)
export const Upload = make(H.Upload01Icon)
export const Volume2 = make(H.VolumeHighIcon)
export const Workflow = make(H.WorkflowSquare01Icon)
export const Wrench = make(H.Wrench01Icon)
export const X = make(H.Cancel01Icon)
export const XIcon = make(H.Cancel01Icon)
export const PanelRight = make(H.SidebarRightIcon)
export const LayoutDashboard = make(H.DashboardSquare01Icon)
export const Code = make(H.CodeIcon)
export const Ruler = make(H.RulerIcon)
export const Download = make(H.Download01Icon)
export const Smartphone = make(H.SmartPhone01Icon)
export const Bold = make(H.TextBoldIcon)
export const Italic = make(H.TextItalicIcon)
export const ListBullets = make(H.LeftToRightListBulletIcon)
export const ListNumbers = make(H.LeftToRightListNumberIcon)
export const Heading2 = make(H.Heading02Icon)
export const Heading3 = make(H.Heading03Icon)
export const Pilcrow = make(H.TextIcon)
export const FilePdf = make(H.Pdf01Icon)
